### ISSUE TITLE
The Juno install Using the packstack base on the Centos7.0 Vm 

### ISSUE THREAD

**Issue by xiaonisiji** [redhat-openstack/packstack#1]
Hi all:
    I have an question of Juno install Using the packstack base on the Centos7.0 Vm.

packstack --answer-file=answer.conf  
192.168.105.6_neutron.pp:                         [ ERROR ]  
Applying Puppet manifests                         [ ERROR ]
ERROR : Error appeared during Puppet run: 192.168.105.6_neutron.pp
Error: Could not set 'present' on ensure: Net::ReadTimeout at 110:/var/tmp/packstack/2603c4a5bcfe413b9d258b49e53791f0/modules/neutron/manifests/server/notifications.pp
You will find full trace in log /var/tmp/packstack/20150122-214015-Gc_1ma/manifests/192.168.105.6_neutron.pp.log
Please check log file /var/tmp/packstack/20150122-214015-Gc_1ma/openstack-setup.log for more information
Additional information:
- Time synchronization installation was skipped. Please note that unsynchronized time on server instances might be problem for some OpenStack components.
- Warning: NetworkManager is active on 192.168.105.6. OpenStack networking currently does not work on systems that have the Network Manager service enabled.
- File /root/keystonerc_admin has been created on OpenStack client host 192.168.105.6. To use the command line tools you need to source the file.
- To access the OpenStack Dashboard browse to http://192.168.105.6/dashboard .
  Please, find your login credentials stored in the keystonerc_admin in your home directory.
- To use Nagios, browse to http://192.168.105.6/nagios username: nagiosadmin, password: 270fda6c48624eec
  can anyone help me to solve me?thank you very much.
  --Shen Ni

**Comment by apevec** [comment]
Please report issues in the upstream tracker bugs.launchpad.net/packstack if you can still reproduce with the latest version (Juno is EOL).
