### ISSUE TITLE
packstack stuck at "Testing if puppet apply is finished: compute.pp"

### ISSUE THREAD

**Issue by robertluwang** [redhat-openstack/packstack#3]
I am testing REHL7.3 OSP10 using packstack to deploy 2 nodes: allinone and compute1, they are vm nodes in virtualbox.

allinone 188.28.88.11
compute1 188.28.88.12

it stuck at this point forever:
Testing if puppet apply is finished: 188.28.88.12_compute.pp  [ | ]

from log, it pending at:
cd /usr/share/openstack-puppet/modules
tar --dereference -cpzf - aodh apache ceilometer certmonger cinder concat firewall glance gnocchi heat horizon inifile ironic keystone manila memcached mongodb mysql neutron nova nssdb openstack openstacklib oslo packstack rabbitmq redis remote rsync sahara ssh stdlib swift sysctl tempest trove vcsrepo vswitch xinetd | ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@188.28.88.12 tar -C /var/tmp/packstack/c76c38384385491dbe1513da95139ea7/modules -xpzf -

manually run it in allinone node, got this error
tar: openstack: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

in fact there is openstack_extras module instead of openstack, but tar list only included openstack?

[root@osp10-allinone modules]# ll |grep openstack
drwxr-xr-x. 8 root root 4096 Sep 24 21:09 openstack_extras
drwxr-xr-x. 8 root root 4096 Sep 24 21:09 openstacklib

**Comment by amoralej** [comment]
From upstream perspective, newton (which corresponds to OSP10) is EOL. As you are using OSP10, i'd suggest to log a support case to Red Hat to get proper help.
